version: "3.8"

services:
  postgres:
    container_name: postgres-db
    image: postgres
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=pass

  java-app:
    container_name: java-app
    image: cmmttd/dev-interview-bot:latest
    environment:
      - "SPRING_PROFILES_ACTIVE=production"
      - BOT_TOKEN=${BOT_TOKEN_QUESTIONS}
      - BOT_USERNAME=${BOT_USERNAME_QUESTIONS}
    volumes:
      - $PWD/src/main/resources/content/:/usr/app/content/