version: "3.8"

services:
  postgres:
    container_name: postgres-db
    image: postgres
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=pass
    volumes:
    - $PWD/src/main/resources/val/:/docker-entrypoint-initdb.d/

#  java-app:
#    container_name: java-app
#    image: cmmttd/dev-interview-bot
#    environment:
#      - BOT_TOKEN=${BOT_TOKEN_QUESTIONS}
#      - BOT_USERNAME=${BOT_USERNAME_QUESTIONS}