telegram:
  bot:
    name: ${BOT_NAME}
    token: ${BOT_TOKEN}
spring:
  datasource:
    username: postgres
    password: pass
  jpa:
    database: postgresql
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  sql:
    init:
      platform: postgres
---
spring:
  config:
    activate:
      on-profile: default
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
  jpa:
    show-sql: true
---
spring:
  config:
    activate:
      on-profile: production
  datasource:
    url: jdbc:postgresql://postgres-db/postgres
  jpa:
    show-sql: false
